# -*- coding: utf-8 -*-
"""conversion-demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u3EZ6iuS-gpggfU_iL1P315LoRFkcfXK
"""

# Welcome to the Enverge

## This is a demo of a conversion to Marimo

import pandas as pd

# prompt: generate a sample pandas dataframe with fruits

data = {'Fruits': ['Apple', 'Banana', 'Orange', 'Grape']}
df = pd.DataFrame(data)

df